//
// Generated from shadow-font.png
//

#ifndef SHADOW_FONT_SPRITE_H
#define SHADOW_FONT_SPRITE_H

#define SHADOW_FONT_CHR_ROM                      (uint8_t)(0)
#define SHADOW_FONT_8x0_CHR_ROM                  (uint8_t)(0)
#define SHADOW_FONT_16x0_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_24x0_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_32x0_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_40x0_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_48x0_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_56x0_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_64x0_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_72x0_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_80x0_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_88x0_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_96x0_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_104x0_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_112x0_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_120x0_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_0x8_CHR_ROM                  (uint8_t)(0)
#define SHADOW_FONT_8x8_CHR_ROM                  (uint8_t)(0)
#define SHADOW_FONT_16x8_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_24x8_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_32x8_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_40x8_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_48x8_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_56x8_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_64x8_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_72x8_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_80x8_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_88x8_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_96x8_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_104x8_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_112x8_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_120x8_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_0x16_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_8x16_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_16x16_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_24x16_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_32x16_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_40x16_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_48x16_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_56x16_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_64x16_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_72x16_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_80x16_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_88x16_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_96x16_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_104x16_CHR_ROM               (uint8_t)(0)
#define SHADOW_FONT_112x16_CHR_ROM               (uint8_t)(0)
#define SHADOW_FONT_120x16_CHR_ROM               (uint8_t)(0)
#define SHADOW_FONT_0x24_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_8x24_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_16x24_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_24x24_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_32x24_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_40x24_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_48x24_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_56x24_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_64x24_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_72x24_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_80x24_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_88x24_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_96x24_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_104x24_CHR_ROM               (uint8_t)(0)
#define SHADOW_FONT_112x24_CHR_ROM               (uint8_t)(0)
#define SHADOW_FONT_120x24_CHR_ROM               (uint8_t)(0)
#define SHADOW_FONT_0x32_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_8x32_CHR_ROM                 (uint8_t)(0)
#define SHADOW_FONT_16x32_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_24x32_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_32x32_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_40x32_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_48x32_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_56x32_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_64x32_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_72x32_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_80x32_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_88x32_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_96x32_CHR_ROM                (uint8_t)(0)
#define SHADOW_FONT_104x32_CHR_ROM               (uint8_t)(0)

#endif // SHADOW_FONT_SPRITE_H
